name: Verify PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 'lts'
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ matrix.node-version }}
      - run: pnpm install
      - run: pnpm build
      - run: pnpm check
      - run: pnpm lint
